version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=spacex
      - MYSQL_USER=spacex_user
      - MYSQL_PASSWORD=1234
    ports:
      - '3306:3306'
    volumes:
      - ./schemas:/var/lib/mysql
volumes:
  db:
    driver: local